select *from EMP;

--la mejor praxis es utilizar el nomre de los campos
--ctr+ENTER EJECUTA LA LINEA EN LA ESTAMOS POSICIONADOS

SELECT APELLIDO, OFICIO, SALARIO from EMP;

--ORDENACION DE DATOS, SIEMPRE AL FINAL Y AFECTA AL SELECT
--LA ORDENACION SIEMPRE ES ASCENDENTE. SE PODRIA PONER ASC, PERO NO ES NECESARIO

SELECT * FROM EMP order by APELLIDO;

--OPERACION DESCENDENTE DESC

SELECT * FROM EMP order by APELLIDO DESC;

--ORDENAR PORMAS DE UN CAMPO

SELECT * FROM EMP order by DEPT_NO, OFICIO; 

--FILTRADO DE REGISTROS (MUY IMPORTANTE)
--SE UTILIZAN LOS OPERADORES DE COMPARACION
/*
= igual
>= mayor o igual
<= menor o igual
> mayor
< menor
<> distinto
*/
--Oracle, por defecto, diferencia entre mayusculas y minusculas en sus textos (string/varchar)
--TODO LO QUE NO SEA UN NUMERO SE ESCRIBE ENTRE COMILLAS SIMPLES '...'
--PARA FILTRAR SE UTILIZA LA PALABRA where Y SE ESCRIBBE SOLAMENTE UNA VEZ EN TODA LA CONSULTA
--DESPUES DEL FROM
--MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 10

SELECT * FROM EMP where DEPT_NO=10;

--MOSTRAR TODOS LOS EMPLEADOS CUYO OFICIO SEA DIRECTOR

SELECT * FROM EMP where OFICIO= 'DIRECTOR';

--MOSTRAR TODOS LOS EMPLEADOSCUYO OFICIO SEA DIFERENTE A DIRECTOR
--MAYUS + FIN PARA SELECCIONARLO TODO

SELECT * FROM EMP where OFICIO<> 'DIRECTOR';

--OPERADORES RELACIONALES 
--NOS PERMITEN REALIZAR MAS DE UNA PREGUNTA DENTRO DEUNA CONSULTA
/*
OR --> MUESTRA LOS DATOSDE CADA FILTRO
AND --> TODOS LOS FILTROS DEBEN CUMPLIRSE
NOT --> NEGACION DE UNA CONDICION (EVITARLO SIEMPRE)
*/
--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y QUE SENA DIRECTORES

SELECT * FROM EMP where DEPT_NO=10 AND OFICIO= 'DIRECTOR';
SELECT * FROM EMP where DEPT_NO=10 OR OFICIO= 'DIRECTOR';

--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10 Y DEL DEPARTAMENTO 20

SELECT * FROM EMP where DEPT_NO=10 OR DEPT_NO=20;

--TENEMOS OTROS OPERADORES ADEMAS DE LOS  STANDARD
--BETWEEN MUESTRA LOS DATOS ENTRE UN RANGO INCLUSIVE
--MOSTRAR LOS EMPLEADOS CUYO SALARIO ESTE ENTRE 251000 Y 390000

SELECT * FROM EMP where SALARIO between 251000 and 390000 order by SALARIO;

--PODEMOS HACER LA MISMA CONSULTA CON OPERADORES Y ES EFICIENTE

SELECT * FROM EMP where SALARIO >=251000 and SALARIO<=390000 order by SALARIO;

--LA NEGACION ES ALGO DE LO QUE DEBEMOS HUIR
--MOSTRAR LOS EMPLEADOS QUE NO SEAN DIRECTOR

SELECT * FROM EMP where NOT OFICIO = 'DIRECTOR';

--PODEMOS REALIZAR LA CONSULTA CON OPERADOR 

SELECT * FROM EMP where OFICIO <> 'DIRECTOR';

--EXISTE UN OPERADOR PARA BUSCAR COINCIDENCIAS EN TEXTOS
--NOS PERMITE MEDIANTE CARACTERES ESPECIALES HACER FILTROS EN TEXTOS
/*
% busca cualquier caracter y longitud
_ un caracter cualquiera
? un caracter numéricos
*/
--MOSTRAR LOS EMPLEADOS CUYO APELLIDO COMIENZA EN S

SELECT * FROM EMP where APELLIDO like 's%';--si solo indico s me tiene que devolver el apellido que sea s
--MOSTRAR TODOS LOS EMPLEADOS CUYO APELLIDO CONTENGA 4 LETRAS
SELECT * FROM EMP where APELLIDO like '____'--4 veces el guion bajo

--EXISTE OTRO OPERADOR PARA BUSCAR COINCIDENCIAS DE IGUALDAD EN UN MISMO CAMPO
--CAMPO: in (valor1, valor2)
--MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10, 20 Y 30

SELECT * FROM EMP where DEPT_NO=10 OR DEPT_NO=20 OR DEPT_NO=30
orDEPT_NO=55 OR DEPT_NO=65 OR DEPT_NO=77;

--LA OTRA OPCION DE HACER LA MISMA CONSULTASE HACE CON in

SELECT * FROM EMP where DEPT_NO in (10,20,30,55,65,77);

--TENEMOS EL OPERADOR not in QUE REALIZA LOSMISMO QUE in PERO
--RECUPERA LOS QUE NO COINCIDAN
--MOSTRAR TODOS LOS EMPLEADOS  QUE NO  ESTEN EN EL DEPARTAMENTO 10 Y 20

SELECT * FROM EMP where NOT DEPT_NO in (10,20);--AQUI ESTAMOS USANDO not como negacion
SELECT * FROM EMP where DEPT_NO not in (10,20);

--CAMPOS CALCULADOS
--UN CAMPO CALCULADO ES UNA HERRAMIENTA EN UNA CONSULTA
--UN CAMPO CALCULADO SIEMPRE DEBE TENER UN ALIAS
--SIRVE PARA GENERAR CAMPOS QUE NO EXISTEN EN LA TABLA Y LOS PODEMOS CALCULAR
--UN CAMPO CALCULADO SOLO ES PARA EL CURSOR ES TODO LO QUE VEO ABAJO EN RESULTADOS DE LA CONSULTA)
--MOSTRAR EL APELLIDO, EL SALARIO, COMISION Y EL SALARIO TOTAL (SALARIO+ COMISION)
--DE TODOS LOS EMPLEADOS CUYO SALARIO MAS COMISION SEA MAYOR 344500

SELECT APELLIDO, SALARIO, COMISION, (SALARIO+COMISION) as TOTAL FROM EMP
where (SALARIO+COMISION)>=344500;

--QUEREMOSLA CONSULTA ORIGINAL Y ORDENAR POR ELLA 

SELECT APELLIDO, SALARIO, COMISION, (SALARIO+COMISION) as TOTAL FROM EMP
order by TOTAL; --ESTO FUNCIONA PORQUE ORDER BY LO HACE SOBRE LA CONSULTA Y WHERE FILTRA SOBRE LA TABLA

--CLAUSULA  DISTINCT: SE UTILIZA PARA SELECT Y LO QUE REALIZA ES
--ELIMINAR REPETIDOS DE LA CONSULTA
--MOSTRAR LOS DIFERENTES OFICIOS DE LOS EMPLEADOS

SELECT distinct OFICIO FROM EMP;


          
      